### ISSUE TITLE
Paxel mining level error?

### ISSUE THREAD

**Issue by Aenye** [kwpugh/gobber_forge#10]
The mining level of paxels seems to have an error. 

Gobber pickaxe can mine nether gobber ore, but gobber paxel cannot. 
End gobber paxel / paxel of the stars cannot even mine stone, but end gobber pickaxe can.
Screenshots with Jade tool adequacy enclosed below:
![Paxel fail](https://user-images.githubusercontent.com/8580217/188506782-dd25ebcf-3b24-45f6-a3f9-ff70143b0819.png)
![Pickaxe win](https://user-images.githubusercontent.com/8580217/188506809-5781ec7a-760d-4dc4-b40c-13ff2ba4b3b3.png)

PS: Might be related to this issue getting fixed? https://github.com/kwpugh/gobber_forge/issues/5

**Comment by kwpugh** [comment]
Which version of Gobber?  I just tried 1.19.2 and the end pixel and paxel of stars can mine everything and pretty fast too.

**Comment by kwpugh** [comment]
With Jade:

![2022-09-05_16 34 25](https://user-images.githubusercontent.com/8809210/188514346-77ece825-42d8-418b-b4c8-5a05787b4e49.png)
![2022-09-05_16 34 49](https://user-images.githubusercontent.com/8809210/188514348-8faa32f3-a5a4-4518-b042-aa82287b8d31.png)

**Comment by kwpugh** [comment]
Please post a copy  of your latest log.

**Comment by kwpugh** [comment]
I hit close by mistake.

**Comment by kwpugh** [comment]
I tried the paxels on 1.18.2  and they were fine as well.

**Comment by Aenye** [comment]
Hi,

Thanks for the quick reply. Sorry for the missing info - I'm on 1.19.2, Gobber2-Forge-1.19.2-2.7.13, Forge version forge-1.19.2-43.1.16 (updated to latest a few days ago). Attaching an excerpt from latest.log - there is one error that might be relevant:
[05Sep2022 21:43:06.299] [Worker-Main-8/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag [#minecraft:mineable/axe (from Gobber2-Forge-1.19.2-2.7.13.jar)] as it is missing following references: #minecraft:mineable/axe (from Gobber2-Forge-1.19.2-2.7.13.jar)

[excerpt.log](https://github.com/kwpugh/gobber_forge/files/9497413/excerpt.log)

**Comment by kwpugh** [comment]
Are you using a Gobber datapack?  I'm using 2.7.15 and I do not get those errors.

**Comment by kwpugh** [comment]
I  post of the datapack in the #datapack  channels soon my Discord

**Comment by kwpugh** [comment]
Discord:  https://discord.com/channels/165631551101599744/988790138899427408

**Comment by kwpugh** [comment]
The error doesn't make sense though.

"Couldn't load tag [#minecraft:mineable/axe (from Gobber2-Forge-1.19.2-2.7.13.jar)] as it is missing following references: #minecraft:mineable/axe (from Gobber2-Forge-1.19.2-2.7.13.jar)"

the mineable/axe.json tag would be used if a mod has blocks it adds that need to be mineable by an axe tool, which Gobber does not.  I have no axe.json in my mod because I add no woods.

**Comment by Aenye** [comment]
Thank you very much!
I've also scanned throughall the mods one by one and found the culprit - it's an addon to Macaw's roof mod ( https://www.curseforge.com/minecraft/mc-mods/macaws-roofs-biomes-o-plenty ) - since this one adds some wood and wood-based blocks, I believe it was the reason for the error - once I disabled that mod the error is also gone.

PS: On a side note, thank you for the great mod!

**Comment by kwpugh** [comment]
Glad you found it.  Enjoy the mod.  You might want to share the log and error with that mod authors.
