### ISSUE TITLE
[1.18.2] Gobber ores should have the forge:ores tag

### ISSUE THREAD

**Issue by Drazuam** [kwpugh/gobber_forge#11]
As the title says, the `forge:ores` tag (any any other applicable "vanilla forge" tags) should be added to the ores.  This will improve mod compat for mods that are specifically looking for the forge:ores tag (see: [Create: Infinidrill](https://github.com/Drazuam/create_infinidrill)).

For reference, here are its [current tags](https://i.imgur.com/ttfJu57.png)

**Comment by kwpugh** [comment]
I'm aware of its uses, and I have thus far left them out so as not to make getting gobber ores via automated means so easy.

I will consider though.

**Comment by kwpugh** [comment]
I assume you can added via a datapack if you are so inclined.

**Comment by Drazuam** [comment]
You can add them via a datapack, but not having the tag causes unexpected behavior for the end-user.  A user ended up coming to me, telling me that they can't get my mod working, which ended up being because there was no tag on the gobber ores.  Non-technical users don't tend to make datapacks to fix things like this, so I would recommend adding the tag as a default, and letting pack-makers balance for automation by removing the tag or adding the ore to automation blacklists.  Not having the tag could also break non-automation compat.  Just my 2¢

FWIW, I will blacklist the Gobber ores on the default Create: Infinidrill config if you add the `forge:ores` tag to them.

**Comment by kwpugh** [comment]
they will  be added in next update.
