### ISSUE TITLE
[1.19.2] Ring of Repair and Supplementaries

### ISSUE THREAD

**Issue by JackBinimbul** [kwpugh/gobber_forge#12]
Unfortunately, these two are incompatible.  Having Supplementaries installed makes it so that the Ring of Repair no longer functions.

Your mod is more important to me than theirs, but I would love for them to get along!

**Comment by kwpugh** [comment]
Could you be more specific?  What part of Supplementaries?

**Comment by JackBinimbul** [comment]
I'm not sure, actually.  Is there a way to determine this?

All I know is that I added in Supplementaries (and it's requisite Moonlight Lib) and items were no longer being repaired.  Not in my inventory, my hotbar, or my gear.

I removed Supplementaries (but not Moonlight), restarted the game, and things started repairing again.  I had done nothing else with Supplementaries.  Only started the game with it newly added.

**Comment by kwpugh** [comment]
which versions of Gobber and Supplementaries are you using?

**Comment by JackBinimbul** [comment]
I don't use Gobber and wasn't aware that it existed until I looked up the issues I was having.  I'm strongly considering giving it a go!  I am using the standalone Ring of Repair 1.5.3 for 1.19.2.  I was trying to most up-to-date version of Supplementaries: 2.2.1 for 1.19.2

My Forge is up-to-date as well.

**Comment by kwpugh** [comment]
I'm looking through their source code.  I suspect our common use of the PlayerTickEvent is conflicting somehow, but not sure.  Will need to spend some time looking and testing.

**Comment by kwpugh** [comment]
give this version a try.   I updated it to Forge 43.1.1 and tried with Supplementaries and it worked fine.

[RingOfRepair-Forge-1.19.2-1.5.4.jar.zip](https://github.com/kwpugh/gobber_forge/files/9621813/RingOfRepair-Forge-1.19.2-1.5.4.jar.zip)

**Comment by JackBinimbul** [comment]
Worked without a hitch!  You're awesome.  I'm also using Gobber now and regret not finding it sooner.  The combo gives me new things to do!

**Comment by kwpugh** [comment]
Enjoy.

**Comment by Milkshake-l** [comment]
i am having this issue in 1.16.5 gobber, is it posible to use the fix from that file, and if so where do i put them
