### ISSUE TITLE
[1.16.5?] Use of Armor Plates

### ISSUE THREAD

**Issue by 81937mm** [kwpugh/gobber_forge#13]
The description of the gobber armor says that it can be repaired qith armor plates but there are two things that are left without explanation:

1) How does one actually repaired it, what i mean by this is that it is not explained if me must use anvils for example

2) When you look up armor plate in the search bar on the inventory it appears but it doesn´t show the use of it repairing gobber armor

**Comment by kwpugh** [comment]
Looks like I forgot to change the tool tip on the armors in 1.16.5, they are repaired with ingots, in an anvil, just like vanilla armor

I assume you are using 1.16.5?

I don't think it is worth updating at this point, since 1.18.2 and 1.19.2 are the current releases.

**Comment by kwpugh** [comment]
Fixed tool tips on Gobber and Nether Gobber Armors in v55.

**Comment by 81937mm** [comment]
Yes i am using 1.16.5 Thanks!!
