### ISSUE TITLE
Gobber Weapons and tools

### ISSUE THREAD

**Issue by Brblues** [kwpugh/gobber_forge#14]
Gobber Tools and Weapons dmg in game does not match values on Curse Website.

Gobber Sword on Site is listed at 11 dmg and 2 Speed, in game its 3 dmg and 2 speed
Gobber PickAxe is listed as having 6 dmg, in game its -2 

![image](https://user-images.githubusercontent.com/90118435/192359231-2c251cd2-9ef5-40ab-90a9-bf61116df19d.png)
![image](https://user-images.githubusercontent.com/90118435/192359305-74c78093-396a-4fcc-9a32-9f48379848b6.png)

List of Mods used
![image](https://user-images.githubusercontent.com/90118435/192359618-65f1067f-5587-4adb-af76-8edcb8aa7b4d.png)

**Comment by kwpugh** [comment]
did you upgrade from a pre-1.19.2 version?   Delete the gobber config and restart..  I refactored some things previously.

**Comment by Brblues** [comment]
Yes, this was an update from 1.18.

Deleting the config resolved the issue it seems. Thank you!

![image](https://user-images.githubusercontent.com/90118435/192364777-4a9f8b52-0528-4d4d-b304-90f84b3492d1.png)

**Comment by kwpugh** [comment]
Glad that worked.  Enjoy the mod!
