### ISSUE TITLE
cannot mine

### ISSUE THREAD

**Issue by L337Murd3r** [kwpugh/gobber_forge#15]
gobber ore is not being mined with diamond pickaxe had to spawn gobber item to do so tried on creative too and it just breaks like its a lesser pickaxe

**Comment by kwpugh** [comment]
Gobber requires netherite pickaxe now.

**Comment by CharCharthemonkey** [comment]
can confirm tho u can use a diamond pickaxe to mine the nether version of gobber ore

**Comment by kwpugh** [comment]
Confirmed, I tried and diamond pickaxe mines nether ore.  I will check this out.

**Comment by kwpugh** [comment]
I found the issue, it was a single missing word in the nether ore mining tag name, lol.

Will be fixed in v2.7.24
