### ISSUE TITLE
Recommendations for configuration files

### ISSUE THREAD

**Issue by 48004800** [kwpugh/gobber_forge#16]
I'm glad that gobber has more detailed configuration files.

The current configuration file has some problems for me. The entity attack damage in the mod I use is very high. A maximum armor value of 20 and a maximum armor toughness of 5 are not enough.

The dragon armor can only be synthesized by killing the enderdragon. The mod I use strengthens the enderdragon. I hope to get more powerful dragon armor in return.

**Comment by kwpugh** [comment]
1.18.2 or 1.19.2 ?

**Comment by kwpugh** [comment]
total armor protection is  capped by the game at 30 for all 4 armor pieces.  Are you using a mod that changes the cap?

**Comment by 48004800** [comment]
https://www.curseforge.com/minecraft/mc-mods/attributefix
