### ISSUE TITLE
[1.19.2] ring of repair issue

### ISSUE THREAD

**Issue by CharCharthemonkey** [kwpugh/gobber_forge#17]
unless im misisng something which im 90% sure i am in gobber for 1.19.2 the ring of repair doesnt repair anything

**Comment by kwpugh** [comment]
I just tested this in latest Gobber Forge and it repairs my broken items.  What are you using to test the repair?

**Comment by CharCharthemonkey** [comment]
gobber items vanilla items mystical agriculture items and none repair

**Comment by kwpugh** [comment]
Please post a copy of your latest.log.

Are you playing single player or server?

Are you playing with a downloaded modpack?

**Comment by CharCharthemonkey** [comment]
single player and custom modpack
[latest.log](https://github.com/kwpugh/gobber_forge/files/9792257/latest.log)

**Comment by CharCharthemonkey** [comment]
also i joined the discord so feel free to ping me if needed

**Comment by kwpugh** [comment]
refer to: https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/issues/1059

**Comment by kwpugh** [comment]
This is solved, correct?

**Comment by kwpugh** [comment]
Without further info, closing.

**Comment by CharCharthemonkey** [comment]
sry missed this but yes it got solved it was some weird compat issue
