### ISSUE TITLE
[1.19.2] Silent Gear Support update

### ISSUE THREAD

**Issue by Skaphegor** [kwpugh/gobber_forge#18]
You missed updating the silent gear support. It uses the old harvest level values for gobber ingots.

**Comment by kwpugh** [comment]
Try this;

[gobber2_silent_gear_datapack-1.19.2.zip](https://github.com/kwpugh/gobber_forge/files/9824492/gobber2_silent_gear_datapack-1.19.2.zip)

**Comment by Skaphegor** [comment]
According to JEI, corresponding harvest levels are 7 (Overworld), 8 (Nether) and 8 (End) for Gobber 2 tools.
The datapacks works fine, though. I changed the values to make them match.

I changed the values to make them match.

**Comment by kwpugh** [comment]
I think JEI is reading wrong or something is amiss.  They should be 5 (Gobber), 6 (Nether), and 7 (End).  

Gobber starts after Netherite, which is 4.

I will take a deeper look.

**Comment by kwpugh** [comment]
where are you seeing harvest  level in JEI?   can you post a screenshot?

**Comment by kwpugh** [comment]
I updated the internal datapack of the mod to harvest level 5, 6, and 7.  It will be in next update I push to CurseForge.

**Comment by Skaphegor** [comment]
JEI might be wrong here, but I took this information. 

![2022-10-21_16 39 03](https://user-images.githubusercontent.com/26455012/197222371-01bb91f3-d044-41a7-b9fb-6bbfee3efd3d.png)
![2022-10-21_16 38 52](https://user-images.githubusercontent.com/26455012/197222383-944c7000-3011-4b38-b187-3fd53ac60112.png)
![2022-10-21_16 38 55](https://user-images.githubusercontent.com/26455012/197222390-47d4d6d7-bd82-495d-b4e3-dc6c75f6308a.png)
