### ISSUE TITLE
Gobber ore Spawn rate

### ISSUE THREAD

**Issue by WhatIsGetHub** [kwpugh/gobber_forge#20]
Hello there, 
Am trying to change the Gobber ores spawn rate by decreasing it, it spawns almost every where.
Is there a way to config the spawn rate for it ?

**Comment by kwpugh** [comment]
What did you change?

**Comment by WhatIsGetHub** [comment]
> What did you change?

Haven't changed anything yet, tried to edit to the config files "gobber-general.toml" but haven't saw anything ore related.
Bear in mind that I am using Gobber 2 in a modpack.

**Comment by kwpugh** [comment]
1.19.2 ?

ore spawning is controlled via datapack now.

Which modpack?

**Comment by WhatIsGetHub** [comment]
Yup on 1.19.2
Its my own modpack I worked on. 

Any idea which datapack could do the job (compatible with your mod) ?
I've been searching for one but couldn't find any tbh

**Comment by kwpugh** [comment]
Check the #datapack19 channel on my discord, pre-built data packs there

**Comment by kwpugh** [comment]
https://discord.gg/dJRs7BuT

**Comment by WhatIsGetHub** [comment]
So I downloaded the zip file "gobber2_forge_1.19.2_datapack.zip" > data > gobber2 > worldgen > configured_feature
Then tried to edit "gobber2_ore_configed.json" but honestly haven't understood the variables available to decrease the spawn rate.

I see 
"discard_chance_on_air_exposure": 0.3,
    "size": 7,

are these the ones am supposed to edit or am I doing it wrong ?

**Comment by kwpugh** [comment]
yes.  and you need to adjust the placed feature json for the ore to change the chance value.

**Comment by kwpugh** [comment]
"size:" controls the max amount of ore blocks placed when a vein occurs
"count:" controls the number of chances the mod is given by the game to possibly place a vein during worldgen

![Screen Shot 2022-11-06 at 8 33 08 AM](https://user-images.githubusercontent.com/8809210/200176955-dd821bf4-9509-451e-b08f-b8538c17eb5d.png)
![Screen Shot 2022-11-06 at 8 33 18 AM](https://user-images.githubusercontent.com/8809210/200176957-07f98217-615c-4ba1-a392-56c1650bee96.png)

**Comment by WhatIsGetHub** [comment]
Hello again,
Yes I was testing it yesterday late in the night & figured some of the variables out but wasn't sure about them until you passionately responded to me & verified it.

the only one I haven't figured until now is "discard_chance_on_air_exposure" what does that do ?

**Comment by kwpugh** [comment]
percent chance that an ore will be discarded if the spawn location is exposed to air, like in the new big caves

**Comment by WhatIsGetHub** [comment]
I see
Alright then, I thank you for your precious time & passion on helping a user of your great mod.
Take care & Good luck ;)

**Comment by kwpugh** [comment]
Take care and enjoy playing!
