### ISSUE TITLE
[1.19.2] CoolSimulations' "More Than A Pickaxe" incompatibility

### ISSUE THREAD

**Issue by Dalevridge** [kwpugh/gobber_forge#22]
Forge 43.1.52 
SurvivalPlus 0.1.6h
More Than A Pickaxe 0.1.6c
Gobber 2.7.28

Minecraft not responding on launch, no issue when each mod is run by itself

**Comment by kwpugh** [comment]
I tried those 3 together and it crashed right away on More Than a Pickaxe.

crash report: https://paste.ee/p/gZwqP

MTAP hasn't updated past 1.19.1

**Comment by Dalevridge** [comment]
MTAP dev response: "Thanks for reporting, I’m aware of this issue and am in the midst of developing 0.1.7 which will fix this incompatibility"
