### ISSUE TITLE
[1.19.2] Ring of pyro doesn't work in inventory

### ISSUE THREAD

**Issue by Saereth** [kwpugh/gobber_forge#25]
Gobber 2 Ring of the Pyro specifically states works in inventory, this is not the case, it will only set mobs on fire if held in main hand.

Steps to reproduce
Craft ring of the pyro
Have it in inventory
Nothing happens
Have it in main hand
Mobs set on fire and levitate.

Expected behavior
Mobs to set on fire

**Comment by kwpugh** [comment]
I will  fix the  tooltip,  it should only work  while  in main hand
