### ISSUE TITLE
[1.19.2] Medallion of waterbreathing doesn't work

### ISSUE THREAD

**Issue by Saereth** [kwpugh/gobber_forge#29]
having it in inventory or holding it in your hand/on hotbar neither prevents drowning 

![image](https://user-images.githubusercontent.com/9200909/208717279-cec521f1-2c3b-43ca-9757-c023238b0743.png)

**Comment by rilancaster** [comment]
Same

**Comment by SummitSummit** [comment]
Ditto.
Using the Direwolf20 pack.
Gobber2-Forge-1.19.2-2.7.28

**Comment by choekstr** [comment]
Not working in ATM 8 pack either, so not specific to DW20 1.19 pack.

I tried holding it, offhand, in inventory, on hotbar, in ender chest and it doesn't provide water breathing or immunity from taking damage once breath bubbles run out.

Gobber version: 2.7.28
Forge version: 43.2.3
MC version: 1.19.2

**Comment by XolfWolf** [comment]
Same

**Comment by DigitalWendigo** [comment]
#44

**Comment by Nelson-Guerra-Tech** [comment]
Using Gobber mod and just crafted the Medallion of Water Breathing, it isn't working at all. I have tried reinstalling the mod maybe some corruption was there.
I see the issue has been around for some time.

**Comment by kwpugh** [comment]
I found the problem, will be fixed in next update.
