### ISSUE TITLE
[1.18.2] Conflict between levitation items in Ars-Noveau and Gobber2 mods

### ISSUE THREAD

**Issue by uhloin** [kwpugh/gobber_forge#3]
Need "Ring of Ascent" from Gobber2 in inventory slot 3.
Need "Ring of Acceleration" from Gobber2 in inventory slot 4.
Need "Belt of Levitation" from Ars-Nouveau in Belt-slot.
Press and release '3' to switch to Ring of Ascent, press right mouse button to levitate, release mouse button.
Press and release '4' to switch to Ring of Acceleration, look down, press and hold right mouse button until touch ground. Do not release right button.
Press 'Sneak' button, release it and only then release right mouse button.
Spiral particles appeared and flying infinite time until press 'Jump'+'Sneak'.
I do not know where problem is in Ars or in Gobber and will report the same issue to Ars.

**Comment by kwpugh** [comment]
It seems as those these items cannot exist together without weird side effects.

per Ars Noveau author: https://github.com/baileyholl/Ars-Nouveau/issues/544

Closing.
