### ISSUE TITLE
[1.19.2] Compatibility Error/Problem with Gobber, Silent Gear, and Apotheosis.

### ISSUE THREAD

**Issue by HeavyDeception** [kwpugh/gobber_forge#30]
Versions
Gobber: 2.7.28
Forge: 43.1.57
Modpack: Direwolf20 1.19
Optifine Installed: No

[This is a full error report to the FTB team about the Compatibility Error As there is more than one mod involved.](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2388)

**Comment by kwpugh** [comment]
fixed by other
