### ISSUE TITLE
[1.18.2] unconventional ore registration

### ISSUE THREAD

**Issue by arzadu** [kwpugh/gobber_forge#33]
Hiya! I know this won't get looked at for a while, but I wanted to make the bug report while it was fresh in my mind. It does also apply to Easy Steel.
Basically, something about registering ores in Java (rather than json datapacks) forces some wonky interaction with other mods (discovered when I tried to fix a mod compat issue in kubejs, better explanation from other people here https://discord.com/channels/303440391124942858/1058138201023324261). not super urgent, as it only comes up when modpack makers start trying to meddle, but I figured I'd let you know.

See you in May!

**Comment by arzadu** [comment]
as it happens, the config settings to completely disable ore generation also don't seem to work for either mod, possibly because of this? either way it is nonfunctional

**Comment by kwpugh** [comment]
I  updated  to  the JSON method  for 1.19.x.   I  have no plans to update 1.18.2  mods  anymore except for  critical bug  fixes, which this really  doesn't  rank  as  one.

I couldn't accces the discord link above  due to permission.  which discord  server is it?
