### ISSUE TITLE
How to disable Lucky ores Generation?

### ISSUE THREAD

**Issue by Sakatsuky** [kwpugh/gobber_forge#35]
On 1.18 there was an option on the config to change the ores generation so it was possible to disable them, but on 1.19 i don't anything on the config, is there a way that i can disable the lucky blocks ore genereation?

**Comment by kwpugh** [comment]
Disabling ore gen is done via datapack going forward.  Might check on YouTube

**Comment by Sakatsuky** [comment]
Thank you, i managed to do it!
