### ISSUE TITLE
Ring of growth and Staff of the Farmer makes glow lichen spread way too much.

### ISSUE THREAD

**Issue by Bloomyex** [kwpugh/gobber_forge#38]
I'm part of an SMP server, and in that server there's people who've acquired the ring and staff. But the main issue is, whenever they used it. Any glow lichen nearby would grow exponentially.

It's gone bad to the point that glow lichen has covered entire giant cave systems and even huge chunks around our spawn...

I was wondering if there'd be a way to tweak it so it doesn't work on lichen? Because if not, then we'll have to change the recipe so people can no longer get it.

**Comment by kwpugh** [comment]
Will be fixed in next update

**Comment by Bloomyex** [comment]
> Will be fixed in next update

Neat! Thanks.
