### ISSUE TITLE
The Armor Repair Plate cannot repair gobber armours

### ISSUE THREAD

**Issue by MCQHX** [kwpugh/gobber_forge#41]
![image](https://user-images.githubusercontent.com/120479408/214521492-5b7dbfa3-cbe3-4652-a0b7-d46e7c9653cd.png)
Hello! Recently I noticed that the armor repair plate cannot repair my nether armor on the crafting table. I'm playing in a server and I'm sure that the armor repair plates aren't banned.

**Comment by MCQHX** [comment]
Game version: 1.16.5 Forge: 36.2.39

**Comment by kwpugh** [comment]
Not used anymore, use ingots to repair armor
