### ISSUE TITLE
Gobber2 crashes on initial load/sided_setup event phase. BowUtils and BowModelEventHandler

### ISSUE THREAD

**Issue by Cryoshira** [kwpugh/gobber_forge#43]
Consistantly get the crash attached when trying to launch the game. I'm using the curseforge launcher, and this happens during the red mojang load screen. For some reason, there seems to be an issue along the lines of the BowUtils.setupBowModelProperties and BowModelEventHandler.setModelProperties during sided_setup.

Not too sure how to investigate this much honestly. I run a server myself for some friends and family. The server starts fine and runs fine as well, but client side we get this error.

Please let me know If you need more info.

[crash-2023-01-30_13.55.36-fml.txt](https://github.com/kwpugh/gobber_forge/files/10539125/crash-2023-01-30_13.55.36-fml.txt)

**Comment by Cryoshira** [comment]
Minecraft version is 1.19.2 and forge version is 43.2.0 btw, can't remember if that's in the txt file or not

**Comment by Cryoshira** [comment]
Patient enough to wait, but it is rather bothersome since it keeps us from playing sometimes. Thank you for taking a look into it when you do though 😄

**Comment by kwpugh** [comment]
I cannot replicate this.  I even tried with Iron Bows thinking there might be a conflict with my custom FOV code, but they seem to work fine together.

Is this still happening?

**Comment by kwpugh** [comment]
no further information, closing.
