### ISSUE TITLE
Medallion of Water Breathing doesn't work in 1.19.2-2.7.28 

### ISSUE THREAD

**Issue by kirinosamaa** [kwpugh/gobber_forge#44]
The medal didn't work and I had tried to sneak right-click.I still suffocate in water.The bug still exist when only the mod.

**Comment by Jaeiya** [comment]
I'm having a similar issue with the dragon helmet not giving water breathing, might be a connected problem?

**Comment by DigitalWendigo** [comment]
Same here.

**Comment by kwpugh** [comment]
Will be fixed in next update
