### ISSUE TITLE
Able to mine end gobber with gobber hammer 

### ISSUE THREAD

**Issue by StormyWinds77** [kwpugh/gobber_forge#5]
My friend I'm playing on a server with has mined all the end gobber ore in the first end island with only a gobber hammer. So I really hope there's more that easy to find. Because neither of us even have nether gobber tools yet.

**Comment by kwpugh** [comment]
Which version of Gobber are you using?

**Comment by kwpugh** [comment]
I see what the problem is.  There was a change in the way Forge material tiers work and I forgot a single json for the end goober which caused the end ore to be mineable by any gobber pickaxe.  

I am testing the fix now and will publish a fix release for 1.18.2 and 1.19

**Comment by kwpugh** [comment]
Also, the mining level will change a little bit

- Gobber Ore will require a Nephrite pickaxe
- Nether Gobber Ore will require a Gobber Pickaxe
- End Gobber Ore will require a Nether Gobber pickaxe

**Comment by kwpugh** [comment]
I just published updated on Curseforge for 1.18.2 and 1.19 that fixes the issue.
