### ISSUE TITLE
Right click jump is broken

### ISSUE THREAD

**Issue by Herobattler** [kwpugh/gobber_forge#52]
Right click jump is broken, it goes forever if you hold the right click and go lightspeed

latest 1.19.2 version of this mod

**Comment by kwpugh** [comment]
Which are you referring to?

**Comment by Herobattler** [comment]
The end gobber sword with the jump ability

**Comment by Sul4urx** [comment]
Wait, isn't that intentional? I mean, this bug is easily noticable.

**Comment by kwpugh** [comment]
it is intentional.
