### ISSUE TITLE
Ring of Curing instantly removing the levitation from Ring of Ascent

### ISSUE THREAD

**Issue by stylneo** [kwpugh/gobber_forge#53]
Levitation is counted as a debuff (as it should) by the Ring of Curing, but that makes the levitation effect given by Ring of Ascent to be instantly removed, making it unusable.

Perhaps whitelist potion effects caused by the player themselves, even if not beneficial for the Ring of Curing.

**Comment by Sul4urx** [comment]
I mean you can remove the levitation effect with the ascent anyways, so the levitation effect should not be listed as "negative"

**Comment by kwpugh** [comment]
I want to keep it on the Ring of Curing
