### ISSUE TITLE
1.18.2 - "Gobber Tree Axe" + "FallingTree" mod - (Axe loses 1 durability per tree.)

### ISSUE THREAD

**Issue by VicinityThree** [kwpugh/gobber_forge#54]
Hi. I've noticed that when using a Gobber Tree Axe in combination with the "FallingTree" mod, the axe only loses 1 durability per tree, instead of calculating the durability damage per log. It seems to only happen to the 3x3 axe, not the others.

**Comment by kwpugh** [comment]
I'm no logger supporting 1.18.2.  This issue has already been addressed in later versions.
