### ISSUE TITLE
[1.16.5] Dragon Armor creative flight bugged

### ISSUE THREAD

**Issue by iamshift** [kwpugh/gobber_forge#6]
Minecraft: 1.16.5
Mod Version: 2.3.54

Starting or changing gamemodes in a non-vanilla dimension disables the use of Dragon Armor creative flight.

**Comment by kwpugh** [comment]
I'll take a look at 1.19.2.   1.16.5 is no longer being updated.   Only 1.18.2 and 1.19.2 are active.

**Comment by kwpugh** [comment]
Also, the creative flight on the armor is only intended to work in vanilla dimensions.

**Comment by kwpugh** [comment]
in 1.18.2+ there is a config option to allow for flight use in any dim.
