### ISSUE TITLE
handle dimension teleporting

### ISSUE THREAD

**Issue by Zonk1987** [kwpugh/gobber_forge#64]
### Minecraft Version

1.19.2

### Modloader

forge-1.19.2-43.2.8

### Mod version

Gobber_Delight_1.1.1_Forge_1.19.2
Gobber2-Forge-1.19.2-2.7.28
jamd-forge-2.0.5-build.12+mc1.19.2

### Repeatable?

- [X] Yes

### Link to log files

there are nothing to see in the logs

### Steps to reproduce the issue

1. Put on the Gobber 2 Full set Dragon Armor
2. Go to the dimension
3. leave the game 
4. join back in the game
5. and now you can not fly anymore

### Description of the issue you are having

Modpack: Direwolf 20 1.19 Version 1.9.0

the issue is described in the steps above.

If you are going back in the overworld and back in the mining dim than you can fly as normaly.

### Information

- [X] I have provided as much information as possible

**Comment by kwpugh** [comment]
By default, the flying ONLY works in the vanilla dims.  If you want other modded dims, there is a config option to enable that.
