### ISSUE TITLE
Feature request: Ring of Repair (standalone mod + gobber integrated) repair while in curio slot

### ISSUE THREAD

**Issue by choekstr** [kwpugh/gobber_forge#65]
It would be really handy if the ring of repair could repair while in the curio slot since it is supported to be placed there. 

Currently the ring doesn't repair if in a curio slot, a handy place to store the ring, and must be removed into general inventory in order to repair.

Additionally repairing off-hand items in the "shield" slot would be nice as well.

Thanks for the consideration

**Comment by Furious1964** [comment]
I second this as that would be awesome.

**Comment by AllMarshall** [comment]
I'm commenting to keep up, I'm quite looking forward to a Ring of Repair that works in the ring slot.

**Comment by ZenAkechi495** [comment]
While this may come off as harassment and quite possibly borders it, I'd also like to add my piece and strongly suggest, that **adding the ability for the ring to repair inventory items from the Curio (ring?) slot would make a huge difference in its utility**.

Reasoning?

No, it is not even the fact it occupies a slot in your regular inventory, it's the fact that inventory sorting mods will toss around the ring(s) I carry in it, when I just want to sort through the regular, pardon my language, garbage I find in it.

The most stylish solution to this, especially considering these rings can already be fitted into said Curio slot, would be to give the user the ability to be blessed by its ability even while carrying it inside such a handy-dandy dedicated spot.

Cheers! And if you find this to be an unnecessary feature, cheers anyways, for you have made my life more pleasant with your mod anways.

**Comment by kwpugh** [comment]
No plans for Curios support.
