### ISSUE TITLE
Dragon Armor gives buggy levitation effect

### ISSUE THREAD

**Issue by uhloin** [kwpugh/gobber_forge#66]
If remove Dragon Armor with pouch (from DivineRPG mod), levitation does not stop.
It place armor back and remove manually, you do not fall to ground and cannot move down but may fly up to ceiling.
If sit to ground and remove Dragon Armor you continue "glide" along the floor like over ice and only death can remove this effect.

**Comment by kwpugh** [comment]
Which version are you using?

**Comment by kwpugh** [comment]
with no more info, I'm not going to try and chase this down.
