### ISSUE TITLE
Placing Gobber Ore in Nether or End doesn't Change Type

### ISSUE THREAD

**Issue by cwade14** [kwpugh/gobber_forge#69]
Hi,

I read that placing Gobber Ore in either the Nether or the End should change the Ore to ether Nether Gobber Ore or End Gobber Ore, respectively. I am not seeing this behavior (stays Gobber ore, even after being mined). Is this a bug or is my information on this feature incorrect?

**Comment by kwpugh** [comment]
That feature was only available in 1.12.2 Minecraft
