### ISSUE TITLE
hold right-click with end gobber sword(with jump ability)

### ISSUE THREAD

**Issue by zDarkChoco** [kwpugh/gobber_forge#72]
on latest 1.19.2 version, when using end gobber sword with jump ability, 

holding the right click make jump go flying if that make sense. if I holding right-click upward then it go fly.
and then we can direct it to other way(while holding right-click) but when we are close to the ground, just point upward and we're flying again. 

it feel almost like flying with elytra. but elytra, they gliding.
this ability is not gliding, look like it continuously jumping even we're not on the ground.

**Comment by Sul4urx** [comment]
This also happens with ring of small and great leaping.

**Comment by kwpugh** [comment]
That is the way it is designed.
