### ISSUE TITLE
Cant make end tools BREAKABLE through config [FORGE]

### ISSUE THREAD

**Issue by gabuly** [kwpugh/gobber_forge#73]
:) My server wants to ban flight of the dragon armor and make end and drag tools breakable, however they seem not to be feasible by changing the config.

**Comment by kwpugh** [comment]
There is a config option to make them breakable when crafted.  Any existing tools will still be unbreakable, but new ones would not.

**Comment by gabuly** [comment]
Thx for replying!  I have already tried changing the config in both server and client as:
#Should Tools be unbreakable when crafted? [true / false, default: true]
	endGobberToolsUnbreakable = false

but newly crafted ones without OP are still unbreakable.....  im confused now

**Comment by qingchunnh** [comment]
Me too

**Comment by kwpugh** [comment]
I'm finally getting around to fixing this for 1.20.1

**Comment by kwpugh** [comment]
fixed in latest update
