### ISSUE TITLE
[1.18.2] Solution to issues with Gobber/Tetra interactions

### ISSUE THREAD

**Issue by arzadu** [kwpugh/gobber_forge#8]
For a while, I have been attempting to resolve issues with Tetra tools not properly interacting with Gobber ores. Tetra tools made of Gobber materials won't mine nether and end gobber ores, regardless of the material used (including ones of a sufficient or higher tier). 

I'm not entirely sure why this works, but changing the compatibility .json files from `"key": "gobber_nether"` to `"key": "nether_gobber"` (for each file, respectively). Essentially, `"key"` has to correspond to the toolLevel, not the material. In addition to this change, adding `data/tetra/tiers/gobber2.json` allows Tetra to accept those material tiers properly. 

The tetra file that I made that works is attached below, feel free to use it directly. Nothing in the compat files has been changed other than the keys.

[tetra.zip](https://github.com/kwpugh/gobber_forge/files/9419016/tetra.zip)

**Comment by mickelus** [comment]
Cmon bud... I've repeatedly told you what the issue was, why are you making things up? :/

The keys for the materials are irrelevant, to get things to play you need to:
 * place a json with an array of your tier ids in `data/tetra/tiers/`, actual filename doesn't matter but modid.json would be good
 * update `toolLevel` in your materials to reference your tiers instead of using numerical values

I'd also skip registering your end tier with tetra as it doesn't add any harvestable blocks as that would make it mesh better with other mods.

**Comment by mickelus** [comment]
Was gonna PR but there was not actual source in the repo 😅 

Add `data/tetra/tiers/gobber2.json`
```json
[
  "gobber2:overworld_gobber",
  "gobber2:nether_gobber"
]
```

Update the `toolLevel` line in `data/tetra/materials/metal/compat/gobber_end.json` to
```json
  "toolLevel": "gobber2:nether_gobber",
```

**Comment by arzadu** [comment]
Hiya mickelus! thanks for correcting the parts that i'm wrong about. I'm quite new to the world of Minecraft datapacks, so this is definitely a learning experience. I made something that worked, without entirely knowing why, and let kwpugh know. Some of my response was "making stuff up," as I wasn't sure why it worked, but it served the function it was meant to. 
rest assured that this is the last time you'll be hearing from me, as you seem to be quite fed up with my crime of asking questions when i don't understand something.

**Comment by mickelus** [comment]
Why are you closing the issue?

I have no problem with you asking questions, I think it's great. But you not listening to the answers and your need to blame others when something's not working is frustrating to deal with.

**Comment by kwpugh** [comment]
I  got it.  Updating the builtin support for Tetra.
