### ISSUE TITLE
Armor perks 1.19.2

### ISSUE THREAD

**Issue by Majkel64** [kwpugh/gobber_forge#82]
Hello,
I have a little problem with turning on perks on Gobber/NetherGobber/EndGobber/Dragon armor.  I have downloaded JD - Gui, but all I can do is to view the endless lines of code. There is no way to edit a single thing. Situation got even worse when I have realised I am not sure for what exact lines I am looking for :D.  After 2 hours of searching I gave up. Could anyone help me? At least tell me where to look for these lines? Thank you in advance.
Btw #1 I simply love this mod, but it would be GREATER :D with these features. I'm about to make the NetherGobber Armor on my survival single-player world and it lacks this fire protect as hell ;D
Btw #2 I have checked version 1.19 and everything works there as it should. No need to dive into the cfg.
Btw #3 Both Gobber and NetherGobber armors give no fall damage when equipped. Should it work like this?

**Comment by kwpugh** [comment]
all other issues are covered by existing issue tickets
