### ISSUE TITLE
The game crashed whilst ticking entity Error: java.lang.NullPointerException: Registry Object not present: gobber2:gobber2_ring_ascent

### ISSUE THREAD

**Issue by thenarrator185** [kwpugh/gobber_forge#86]
Server on 1.20.1  Forge 

Hello so the code came as such    java.lang.NullPointerException: Registry Object not present: gobber2:gobber2_ring_ascent
Gobber 2 (gobber2), Version: 2.8.3    

Don't know what happened, but I think it was also due to (fall protection) being on some iron boots.
hens the code I received after the Minecraft launcher crashed and booting me off a game server with other mods included with this one.
TRANSFORMER/gobber2@2.8.3/com.kwpugh.gobber2.util.PlayerEquipsUtil.isPlayerGotFallProtection(PlayerEquipsUtil.java:133)

All other mods worked together and with this mod we have been testing them and been working fine till now, I am currently on the server with no issues but I have a feeling that if I do another 3 - 4 block fall it will run the script again and boot me off.

Hope this could help.

**Comment by kwpugh** [comment]
I need a full crash report file.
