### ISSUE TITLE
Description: Container click

### ISSUE THREAD

**Issue by thenarrator185** [kwpugh/gobber_forge#87]
server 1.20.1

Thread: Render thread
Suspected Mod: 
	Gobber 2 (gobber2), Version: 2.8.3
		at TRANSFORMER/gobber2@2.8.3/com.kwpugh.gobber2.util.handlers.AnvilEventHandler.upgradeSomeTools(AnvilEventHandler.java:27)

Details:
	Menu Type: minecraft:anvil
	Menu Class: net.minecraft.world.inventory.AnvilMenu
	Slot Count: 39
	Slot: -999
	Button: 6
	Type: QUICK_CRAFT

Tried to name something real quick and the game crashed again. interfering with a naming of a repulsion gadget of another mod.

**Comment by kwpugh** [comment]
need a crash report
